app:
    path: /
    defaults:
        _controller: AppBundle:App:index

app_bundle:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

app_bundle_api:
    type: rest
    resource: 'AppBundle\Controller\ApiController'
    prefix: /rest-api

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc