app_cluster_index:
    path: /
    defaults:
        _controller: 'AppBundle:Resource:index'
        _entity: '%app.cluster.class%'
    methods: ['GET']

app_cluster_show:
    path: /{id}/show
    defaults:
        _controller: 'AppBundle:Resource:show'
        _entity: '%app.cluster.class%'
    requirements:
        id: \d
    methods: ['GET']

app_cluster_create:
    path: /new
    defaults:
        _controller: 'AppBundle:Resource:create'
        _form: '%app.cluster.form%'
    methods: ['GET', 'POST']

app_cluster_update:
    path: /{id}/edit
    defaults:
        _controller: 'AppBundle:Resource:edit'
        _form: '%app.cluster.form%'
        _entity: '%app.cluster.class%'
        _redirect: 'app_cluster_index'
    requirements:
        id: \d
    methods: ['GET', 'PUT']

app_cluster_delete:
    path: /{id}/delete
    defaults:
        _controller: 'AppBundle:Resource:delete'
        _entity: '%app.cluster.class%'
        _redirect: 'app_cluster_index'
    requirements:
        id: \d
    methods: ['GET', 'DELETE']