app_note_index:
    path: /
    defaults:
        _controller: 'AppBundle:Resource:index'
        _entity: '%app.cluster.class%'
    methods: ['GET']

app_note_show:
    path: /{id}/show
    defaults:
        _controller: 'AppBundle:Resource:show'
        _entity: '%app.cluster.class%'
    requirements:
        id: \d
    methods: ['GET']

app_note_create:
    path: /new
    defaults:
        _controller: 'AppBundle:Resource:create'
        _form: '%app.note.form%'
    methods: ['GET', 'POST']

app_note_update:
    path: /{id}/edit
    defaults:
        _controller: 'AppBundle:Resource:edit'
        _form: '%app.note.form%'
        _entity: '%app.note.class%'
    requirements:
        id: \d
    methods: ['GET', 'PUT']

app_note_delete:
    path: /{id}/delete
    defaults:
        _controller: 'AppBundle:Resource:delete'
        _entity: '%app.note.class%'
    requirements:
        id: \d
    methods: ['DELETE']