app_workspace_index:
    path: /
    defaults:
        _controller: 'AppBundle:Resource:index'
        _entity: '%app.workspace.class%'
    methods: ['GET']

app_workspace_show:
    path: /{id}/show
    defaults:
        _controller: 'AppBundle:Resource:show'
        _entity: '%app.workspace.class%'
    requirements:
        id: \d+
    methods: ['GET']

app_workspace_create:
    path: /new
    defaults:
        _controller: 'AppBundle:Resource:create'
        _form: '%app.workspace.form%'
    methods: ['GET', 'POST']

app_workspace_update:
    path: /{id}/edit
    defaults:
        _controller: 'AppBundle:Resource:edit'
        _form: '%app.workspace.form%'
        _entity: '%app.workspace.class%'
        _redirect: 'app_workspace_index'
    requirements:
        id: \d+
    methods: ['GET', 'PUT']

app_workspace_delete:
    path: /{id}/delete
    defaults:
        _controller: 'AppBundle:Resource:delete'
        _entity: '%app.workspace.class%'
        _redirect: 'app_workspace_index'
    requirements:
        id: \d+
    methods: ['GET', 'DELETE']